### ISSUE TITLE
Add Awards to homepage slider

### ISSUE THREAD

**Issue by dharmishta** [codeforamerica/awards#20]
{
"page_link"     : "http://awards.codeforamerica.org",
"title"         : "Code for America Technology Awards",
"content_html"  : "The Code for America Technology Awards recognize outstanding examples of government technology. Companies, government entities, groups, and individuals are eligible to apply. Recipients will be recognized on stage on September 30 - October 2 at the Code for America Summit in Oakland, CA.",
"image_src"     : "",
"button_text"   : "Learn more"
},

Do you have an idea for an image to use?

**Comment by dharmishta** [comment]
Also feel free to shorten the text if it's too long :smile:

**Comment by davidrleonard** [comment]
Closed in codeforamerica/codeforamerica.org#1154
